---
- src: geerlingguy.ntp
- src: geerlingguy.mysql
- src: geerlingguy.nginx
- src: geerlingguy.php
- src: geerlingguy.php-mysql
- src: tersmitten.wordpress
- name: ansible-network-interfaces
  src: https://github.com/dresden-weekly/ansible-network-interfaces
- name: leucos.mysql
  src: https://github.com/leucos/ansible-pxc
